apiVersion: v2
name: reference-data-setup-eks
description: A Helm chart for Installation of Reference Data

type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
  - name: reference-data-setup
    repository: file://../../component-charts/reference-data-setup-generic
    version: "1.0.0"