global:
  awsRegion: "us-east-1"
  nfs:
    fileSystemId: fileSystemId
    ## Create storage class as part of chart
    storageClass:
      enabled: true
      ## external storage class name if not created as part of chart
      name: ~

reference-data:
  config:
    dataConfigMap: "{\"verify-geocode\":{\"usa\":[\"Geocoding MLD US#United States#All USA#Spectrum Platform Data\",\"Geocoding NT Street US#United States#All USA#Spectrum Platform Data\"],\"aus\":[\"Geocoding PSMA Street#Australia#All AUS#Geo Addressing Reference Data\",\"Geocoding GNAF Address Point#Australia#All AUS#Geo Addressing Reference Data\"]},\"lookup\":{\"usa\":[\"Geocoding MLD US#United States#All USA#Spectrum Platform Data\",\"Geocoding NT Street US#United States#All USA#Spectrum Platform Data\",\"Geocoding Reverse PRECISELYID#United States#All USA#Spectrum Platform Data\"],\"aus\":[\"Geocoding PSMA Street#Australia#All AUS#Geo Addressing Reference Data\",\"Geocoding GNAF Address Point#Australia#All AUS#Geo Addressing Reference Data\"]},\"autocomplete\":{\"usa\":[\"Predictive Addressing Points#United States#All USA#Interactive\"],\"aus\":[\"Predictive Addressing Points#Australia#All AUS#Interactive\"]},\"express_data\":{\"usa\":[\"Address Express#United States#All USA#Spectrum Platform Data\",\"POI Express#United States#All USA#Spectrum Platform Data\"],\"aus\":[\"Address Express#Australia#All AUS#Spectrum Platform Data\"]}}"