{{- if .Values.enabled }}
{{- if .Values.autoscaling.enabled }}
{{- $top := . -}}
{{- range $.Values.global.countries }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "lookup-svc.fullname" (list $top .) }}
  labels:
    {{- include "lookup-svc.labels" (list $top .) | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "lookup-svc.fullname" (list $top .) }}
  minReplicas: {{ $top.Values.autoscaling.minReplicas }}
  maxReplicas: {{ $top.Values.autoscaling.maxReplicas }}
  metrics:
    {{- if $top.Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ $top.Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
{{- end }}
{{- end }}
{{- end }}
