enabled: ~

serviceAccount:
  annotations: { }

dataVintage:
  image:
    repository: bitnami/kubectl
    pullPolicy: Always
    tag: latest
    pullSecrets: [ ]

  configMap:
    name: addressing-data-mnt-config